export const PRODUCTS = [
  { id: 1, name: 'Product 1', price: 100, description: 'Description for product 1', imageUrl: '/images/1.jpg' },
  { id: 2, name: 'Product 2', price: 200, description: 'Description for product 2', imageUrl: '/images/2.jpg' },
  { id: 3, name: 'Product 3', price: 300, description: 'Description for product 3', imageUrl: '/images/3.jpg' },
  { id: 4, name: 'Product 4', price: 400, description: 'Description for product 4', imageUrl: '/images/4.jpg' },
  { id: 6, name: 'Product 6', price: 600, description: 'Description for product 6', imageUrl: '/images/1.jpg' },
  { id: 5, name: 'Product 5', price: 500, description: 'Description for product 5', imageUrl: '/images/2.jpg' },
  { id: 7, name: 'Product 7', price: 700, description: 'Description for product 7', imageUrl: '/images/3.jpg' },
  { id: 8, name: 'Product 8', price: 800, description: 'Description for product 8', imageUrl: '/images/4.jpg' },
  { id: 9, name: 'Product 9', price: 900, description: 'Description for product 9', imageUrl: '/images/1.jpg' },
  { id: 10, name: 'Product 10', price: 1000, description: 'Description for product 10', imageUrl: '/images/2.jpg' },
  { id: 11, name: 'Product 11', price: 1100, description: 'Description for product 11', imageUrl: '/images/3.jpg' },
  { id: 12, name: 'Product 12', price: 1200, description: 'Description for product 12', imageUrl: '/images/4.jpg' },
  { id: 13, name: 'Product 13', price: 1300, description: 'Description for product 13', imageUrl: '/images/1.jpg' },
  { id: 14, name: 'Product 14', price: 1400, description: 'Description for product 14', imageUrl: '/images/2.jpg' },
  { id: 15, name: 'Product 15', price: 1500, description: 'Description for product 15', imageUrl: '/images/3.jpg' },
  { id: 16, name: 'Product 16', price: 1600, description: 'Description for product 16', imageUrl: '/images/4.jpg' },
  { id: 17, name: 'Product 17', price: 1700, description: 'Description for product 17', imageUrl: '/images/1.jpg' },
  { id: 18, name: 'Product 18', price: 1800, description: 'Description for product 18', imageUrl: '/images/2.jpg' },
  { id: 19, name: 'Product 19', price: 1900, description: 'Description for product 19', imageUrl: '/images/3.jpg' },
  { id: 20, name: 'Product 20', price: 2000, description: 'Description for product 20', imageUrl: '/images/4.jpg' },
];
